version: "3.5"

services:
  fastapi:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    command: hypercorn --bind 0.0.0.0:7000 --reload main:app
    container_name: "fastapi"
    ports:
      - "7000:7000"
    volumes:
      - ./app:/app
